services:
  api-consultas-datalake:
    build: .
    image: br4yangc/cloud-computing-project-ms-5:api-consultas
    container_name: api-consultas-datalake
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      # AWS Configuration (IAM Role usado en EC2, no necesita credenciales explícitas)
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      # Athena Configuration
      - AWS_ATHENA_DATABASE=${AWS_ATHENA_DATABASE:-cloud_bank_db}
      - AWS_ATHENA_OUTPUT_LOCATION=${AWS_ATHENA_OUTPUT_LOCATION}
      - ATHENA_WORKGROUP=${ATHENA_WORKGROUP:-primary}
      # API Configuration
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-8000}
      - API_RELOAD=${API_RELOAD:-false}
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    restart: unless-stopped
